name: Publish Artifact

on:
  push:
    branches: [ "master" ]

concurrency:
  group: "publish"
  cancel-in-progress: true

jobs:
  linux:
    strategy:
      matrix:
        include:
          - container: ubuntu:14.04
            arch: x86-64
            src_dir: /usr/lib/x86_64-linux-gnu/libopus.so.0
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.container }}
    steps:
      - name: Install libopus from APT
        run: apt install libopus0
      - name: Copy Shared Library
        run: cp ${{ matrix.src_dir }} natives/src/main/resources/linux-${{ matrix.arch }}/libopus.so
  build:
      needs: linux
      runs-on: ubuntu-latest
      steps:
        - name: Checkout sources
          uses: actions/checkout@v2
        - name: Make gradlew executable
          run: chmod u+x gradlew
        - name: Build jar
          run: ./gradlew --console plain --stacktrace build
        - name: Upload Artifact
          uses: actions/upload-artifact@v3
          with:
            name: opus-java-natives.jar
            path: natives/build/libs/*.jar
    
