name: Publish Artifact

on:
  push:
    branches: [ "master" ]

concurrency:
  group: "publish"
  cancel-in-progress: true

jobs:
  linux:
    strategy:
      matrix:
        include:
          - container: ubuntu:14.04
            arch: x86-64
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.container }}
    steps:
      - name: Install libopus from APT
        run: apt install libopus0
      - name: Copy Shared Library
        run: cp "$(find /usr/lib -name libopus.so.0 -print)" libopus.so
      - name: Upload Artifact ${{ matrix.arch }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.arch }}-libopus.so
          path: libopus.so
  build:
      needs: linux
      runs-on: ubuntu-latest
      steps:
        - name: Checkout sources
          uses: actions/checkout@v2
        - name: Download Artifacts
          uses: actions/download-artifact@v3
          with:
            path: .
        - name: Move Artifacts
          run: |
            mkdir -p natives/src/main/resources/linux-x86-64-test
            mv x86-64-libopus.so natives/src/main/resources/linux-x86-64-test/libopus.so
        - name: Make gradlew executable
          run: chmod u+x gradlew
        - name: Build jar
          run: ./gradlew --console plain --stacktrace build
        - name: Upload Artifact
          uses: actions/upload-artifact@v3
          with:
            name: opus-java-natives.jar
            path: natives/build/libs/*.jar
    
